import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { MODULE_BUILD_DIR } from '../module/build.js';

/** The directory the kit owns inside a consumer repo — `.e2e-kit`, the parent of `module-build`. */
const KIT_DIR = path.dirname(MODULE_BUILD_DIR);

/**
 * Minimal shape this module reads. Deliberately structural rather than importing `E2EConfig`, so the
 * generator can be unit-tested with a literal.
 */
interface SuitesShape {
  suites?: { custom?: string };
}

/**
 * The directory Playwright should scan for the consumer's specs.
 *
 * Derived from `suites.custom` by taking everything before the first glob character — so
 * `e2e/specs/ * * / *.spec.ts` yields `e2e/specs`. Falls back to `<configDir>/specs`, which is the
 * layout spec §5.1 documents.
 */
export function resolveSpecDir(cwd: string, config: SuitesShape, configPath: string): string {
  const glob = config.suites?.custom;
  if (!glob) return path.resolve(path.dirname(configPath), 'specs');

  const firstGlobChar = glob.search(/[*?[]/);
  const literal = firstGlobChar === -1 ? glob : glob.slice(0, firstGlobChar);
  // `e2e/specs/` -> `e2e/specs`; `tests/*.spec.ts` -> `tests/` -> `tests`.
  const trimmed = literal.replace(/[/\\]+$/, '');
  return path.resolve(cwd, trimmed || '.');
}

/**
 * Generate the Playwright configuration inside `.e2e-kit/`, and return its path.
 *
 * Two problems this solves at once (DECISIONS.md D-034):
 *
 *  1. **The consumer no longer needs to write one.** Spec §5.1 promises a two-file adoption, but
 *     `e2e-kit test` required a third file — a `playwright.config.ts` that is pure boilerplate, since
 *     everything in it is already declared in `e2e.config.ts`.
 *  2. **It loads in a CommonJS consumer.** Playwright chooses a config's module format from the nearest
 *     `package.json` `type`. `@invertus/e2e-core` is ESM-only — its `exports` map has no `require`
 *     condition — so a hand-written config in a CJS repo (a PrestaShop module shipping Cypress, say)
 *     fails with `No "exports" main defined`. Writing a `package.json` containing `{"type":"module"}`
 *     beside the generated config makes **this directory** ESM regardless of what the consumer's own
 *     package says, so the `import` condition matches.
 *
 * Paths in the generated file are absolute because it does not sit next to the consumer's config.
 */
export function synthesizePlaywrightConfig(opts: {
  cwd: string;
  config: SuitesShape;
  configPath: string;
}): string {
  const dir = path.resolve(opts.cwd, KIT_DIR);
  mkdirSync(dir, { recursive: true });

  // Scoped to this directory only — it does not affect the consumer's own package type.
  writeFileSync(
    path.join(dir, 'package.json'),
    `${JSON.stringify({ type: 'module' }, null, 2)}\n`,
    'utf8',
  );

  // The `.e2e-kit/` marker above only governs files inside `.e2e-kit/`. The consumer's own
  // `e2e/e2e.config.ts`, `e2e/psp/*.ts` and `e2e/specs/*.spec.ts` all import the kit as well, and
  // Playwright loads each of them according to the nearest package.json — the consumer's, which may be
  // CommonJS. So the directory holding those files needs the same marker.
  //
  // This is safe because `e2e/` contains only kit-related files by construction (spec §5.1), and a
  // package.json with just a `type` affects module format only — Node still walks up for node_modules.
  // Never overwrite an existing one: that would be the consumer's own file.
  const configDir = path.dirname(path.resolve(opts.configPath));
  const consumerMarker = path.join(configDir, 'package.json');
  // Only if the directory is really there — the kit does not create the consumer's own directories.
  if (existsSync(configDir) && !existsSync(consumerMarker)) {
    writeFileSync(consumerMarker, `${JSON.stringify({ type: 'module' }, null, 2)}\n`, 'utf8');
  }

  const specDir = resolveSpecDir(opts.cwd, opts.config, opts.configPath);
  const configFile = path.join(dir, 'playwright.config.ts');

  writeFileSync(
    configFile,
    `// GENERATED by e2e-kit — do not edit, and do not commit.
//
// Spec §5.1's two-file adoption means the consumer declares everything in e2e.config.ts; this file is
// the boilerplate that used to be copied into every repo. It lives beside a package.json declaring
// {"type":"module"} so Playwright loads it as ESM even when the consumer package is CommonJS
// (DECISIONS.md D-034).
//
// To customise, write your own playwright.config.ts in the repo root — the CLI prefers it over this —
// or pass --playwright-config.
import { definePlaywrightConfig } from '@invertus/e2e-core';
import config from ${JSON.stringify(opts.configPath)};

export default definePlaywrightConfig({
  config,
  testDir: ${JSON.stringify(specDir)},
});
`,
    'utf8',
  );

  return configFile;
}
