#!/usr/bin/env node
/**
 * Build the platform images locally (spec §4.1, §4.3, §6.4).
 *
 * Steps: compile the adapter package -> emit the seed manifest from `dataset.ts` ->
 * ensure the E2E CA and its leaf certificates exist -> `docker build` the requested
 * PrestaShop targets -> `docker build` the provider mock images.
 *
 * The mock images are built in the same invocation on purpose: the PS image trusts a CA
 * generated by `gen-ca.mjs`, and the mock serves a leaf signed by that same CA. Built apart,
 * they drift and the only symptom is an opaque TLS failure inside PHP.
 *
 * Usage: node scripts/build-image.mjs [--ps 8] [--no-cache] [--all] [--mocks-only]
 */

import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const matrixPath = path.join(repoRoot, 'images', 'prestashop', 'build-matrix.json');
const matrix = JSON.parse(readFileSync(matrixPath, 'utf8'));

const argv = process.argv.slice(2);
const psArgIndex = argv.indexOf('--ps');
const requestedTag = psArgIndex >= 0 ? argv[psArgIndex + 1] : undefined;
const buildAll = argv.includes('--all');
const noCache = argv.includes('--no-cache');
const mocksOnly = argv.includes('--mocks-only');

/**
 * Provider mock images (spec §6.4). Each entry's `hosts` are the hostnames the mock answers to
 * inside the compose network, and therefore the leaf certificates `gen-ca.mjs` must issue.
 * Onboarding a future provider mock is one entry here — no other kit change (§6.4 item 3).
 */
const MOCK_IMAGES = [
  { name: 'mollie-mock', tag: 'e2e-mock-mollie:latest', hosts: ['api.mollie.com'] },
];

const targets = mocksOnly
  ? []
  : buildAll
    ? matrix.targets
    : matrix.targets.filter((t) => t.tag === (requestedTag ?? '8'));

if (!mocksOnly && targets.length === 0) {
  console.error(
    `No target matches --ps ${requestedTag}. Known tags: ${matrix.targets.map((t) => t.tag).join(', ')}`,
  );
  process.exit(1);
}

function sh(cmd, args, opts = {}) {
  console.log(`\n\x1b[1;34m$\x1b[0m ${cmd} ${args.join(' ')}`);
  execFileSync(cmd, args, { stdio: 'inherit', cwd: repoRoot, ...opts });
}

// 1. The manifest is generated from dataset.ts, so the adapter must be compiled first.
if (!mocksOnly) {
  sh('npm', ['run', 'build', '-w', '@invertus/e2e-prestashop']);

  const { serialiseSeedManifest } = await import(
    path.join(repoRoot, 'packages', 'prestashop', 'dist', 'seed', 'index.js')
  );
  const manifestOut = path.join(repoRoot, 'images', 'prestashop', 'seed', 'manifest.json');
  mkdirSync(path.dirname(manifestOut), { recursive: true });
  writeFileSync(manifestOut, serialiseSeedManifest(), 'utf8');
  console.log(`[build-image] wrote ${path.relative(repoRoot, manifestOut)}`);
}

// 2. The CA and every mock's leaf must exist before any image build copies them in
//    (DECISIONS.md D-009).
const hostArgs = MOCK_IMAGES.flatMap((mock) => mock.hosts.flatMap((host) => ['--host', host]));
sh('node', ['scripts/gen-ca.mjs', ...hostArgs]);

// 3. Build each requested target.
for (const target of targets) {
  const imageTag = `e2e-ps:${target.tag}`;
  const args = [
    'build',
    '--platform', matrix.platform,
    '-f', 'images/prestashop/Dockerfile',
    '-t', imageTag,
    '--build-arg', `PS_BASE=${target.base}`,
    '--build-arg', `PS_MAJOR=${target.tag}`,
    ...(noCache ? ['--no-cache'] : []),
    '--progress', 'plain',
    '.',
  ];
  sh('docker', args);
  console.log(`\n\x1b[1;32m[build-image] built ${imageTag} from ${target.base}\x1b[0m`);
}

// 4. Provider mocks. Same platform as the shop so a single-arch runner never mixes arches.
for (const mock of MOCK_IMAGES) {
  sh('docker', [
    'build',
    '--platform', matrix.platform,
    '-f', `images/${mock.name}/Dockerfile`,
    '-t', mock.tag,
    ...(noCache ? ['--no-cache'] : []),
    '--progress', 'plain',
    '.',
  ]);
  console.log(`\n\x1b[1;32m[build-image] built ${mock.tag} (serves ${mock.hosts.join(', ')})\x1b[0m`);
}
